import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { toast } from 'sonner';
import { FileText, Download, Plus, Calendar, TrendingDown } from 'lucide-react';

export default function Insurance() {
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();

  const { data: claims } = useQuery({
    queryKey: ['insurance-claims'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('insurance_claims')
        .select(`
          *,
          field:fields(name, crop_type, acreage),
          assessment:assessments(health_score, stress_level, analyzed_at)
        `)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data;
    }
  });

  const { data: fields } = useQuery({
    queryKey: ['fields'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('fields')
        .select('*')
        .order('name');
      
      if (error) throw error;
      return data;
    }
  });

  const createClaim = useMutation({
    mutationFn: async (formData: FormData) => {
      const { error } = await supabase.from('insurance_claims').insert([{
        field_id: formData.get('field_id') as string,
        event_type: formData.get('event_type') as string,
        event_date: formData.get('event_date') as string,
        estimated_loss_percentage: Number(formData.get('estimated_loss_percentage')),
        description: formData.get('description') as string,
        status: 'draft'
      }]);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['insurance-claims'] });
      toast.success('Insurance claim created');
      setOpen(false);
    }
  });

  const exportClaim = async (claimId: string) => {
    const claim = claims?.find(c => c.id === claimId);
    if (!claim) return;

    const report = `
CROP INSURANCE CLAIM REPORT
Generated: ${new Date().toLocaleDateString()}

CLAIM INFORMATION
Claim ID: ${claim.id}
Event Type: ${claim.event_type}
Event Date: ${new Date(claim.event_date).toLocaleDateString()}
Status: ${claim.status}

FIELD INFORMATION
Field Name: ${claim.field?.name}
Crop Type: ${claim.field?.crop_type}
Acreage: ${claim.field?.acreage}

DAMAGE ASSESSMENT
Estimated Loss: ${claim.estimated_loss_percentage}%
${claim.assessment ? `Health Score: ${claim.assessment.health_score}/100` : ''}
${claim.assessment ? `Stress Level: ${claim.assessment.stress_level}` : ''}
${claim.assessment ? `Analysis Date: ${new Date(claim.assessment.analyzed_at).toLocaleDateString()}` : ''}

DESCRIPTION
${claim.description || 'No additional description provided'}

---
This report was generated by AgurateAI Crop Management System
AI-powered crop health analysis for Louisiana Delta agriculture
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `insurance-claim-${claim.id.substring(0, 8)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Claim report downloaded');
  };

  return (
    <div className="min-h-screen bg-gradient-subtle pb-24">
      <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
        <div className="flex justify-between items-start gap-4">
          <div className="flex-1">
            <h1 className="text-4xl font-display font-bold text-gradient-delta">
              Insurance Claims
            </h1>
            <p className="text-muted-foreground mt-2">
              Document and export crop damage for insurance providers
            </p>
          </div>

          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button className="gap-2">
                <Plus className="h-4 w-4" />
                New Claim
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Insurance Claim</DialogTitle>
              </DialogHeader>
              <form onSubmit={(e) => {
                e.preventDefault();
                const formData = new FormData(e.currentTarget);
                createClaim.mutate(formData);
              }} className="space-y-4">
                <div>
                  <Label>Field</Label>
                  <Select name="field_id" required>
                    <SelectTrigger>
                      <SelectValue placeholder="Select field" />
                    </SelectTrigger>
                    <SelectContent>
                      {fields?.map(field => (
                        <SelectItem key={field.id} value={field.id}>
                          {field.name} ({field.crop_type})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Event Type</Label>
                  <Select name="event_type" required>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="flood">Flood</SelectItem>
                      <SelectItem value="drought">Drought</SelectItem>
                      <SelectItem value="hail">Hail</SelectItem>
                      <SelectItem value="wind">Wind Damage</SelectItem>
                      <SelectItem value="disease">Disease Outbreak</SelectItem>
                      <SelectItem value="pest">Pest Infestation</SelectItem>
                      <SelectItem value="other">Other</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Event Date</Label>
                  <Input type="date" name="event_date" required />
                </div>

                <div>
                  <Label>Estimated Loss (%)</Label>
                  <Input type="number" name="estimated_loss_percentage" min="0" max="100" step="0.1" />
                </div>

                <div>
                  <Label>Description</Label>
                  <Textarea name="description" rows={4} placeholder="Describe the damage and circumstances..." />
                </div>

                <Button type="submit" className="w-full">Create Claim</Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        {/* Educational Section */}
        <Card className="field-card bg-primary/5 border-primary/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              What is Insurance Claims Management?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h3 className="font-semibold mb-2">Purpose</h3>
                <p className="text-sm text-muted-foreground">
                  Document crop damage events with AI-backed evidence for faster, more accurate insurance claims. 
                  Link your AgurateAI crop assessments directly to insurance claims to provide objective, 
                  timestamped health data that supports your loss estimates.
                </p>
              </div>
              
              <div>
                <h3 className="font-semibold mb-2">When to Use</h3>
                <ul className="text-sm text-muted-foreground space-y-2">
                  <li className="flex gap-2">
                    <span className="text-primary">•</span>
                    <span>After weather events (flood, drought, hail, wind damage)</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-primary">•</span>
                    <span>Disease outbreak or pest infestation detected by AI</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-primary">•</span>
                    <span>Unexplained crop stress documented over time</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="border-t pt-4">
              <h3 className="font-semibold mb-3">How to Use</h3>
              <div className="grid md:grid-cols-3 gap-4 text-sm">
                <div className="p-3 bg-background rounded-lg">
                  <div className="font-semibold text-primary mb-1">1. Create Claim</div>
                  <p className="text-muted-foreground">
                    Click "New Claim" and select the affected field, event type, and date
                  </p>
                </div>
                <div className="p-3 bg-background rounded-lg">
                  <div className="font-semibold text-primary mb-1">2. Link AI Data</div>
                  <p className="text-muted-foreground">
                    AI assessments from the same field are automatically available as evidence
                  </p>
                </div>
                <div className="p-3 bg-background rounded-lg">
                  <div className="font-semibold text-primary mb-1">3. Export Report</div>
                  <p className="text-muted-foreground">
                    Download formatted report with AI analysis to submit to your insurance provider
                  </p>
                </div>
              </div>
            </div>

            <div className="p-4 bg-green-500/10 border border-green-500/20 rounded-lg">
              <p className="text-sm font-medium text-green-700 mb-1">💰 Estimated Value</p>
              <p className="text-sm text-muted-foreground">
                Farmers with documented AI evidence settle claims <strong>40% faster</strong> and recover 
                <strong> 15-25% more</strong> in payouts due to objective, timestamped crop health data.
              </p>
            </div>
          </CardContent>
        </Card>

        <div className="grid gap-4">
          {claims?.length === 0 ? (
            <Card className="field-card">
              <CardContent className="pt-6 text-center py-12">
                <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                <p className="text-muted-foreground">No insurance claims yet</p>
                <p className="text-sm text-muted-foreground mt-2">
                  Create a claim to document crop damage for insurance providers
                </p>
              </CardContent>
            </Card>
          ) : (
            claims?.map(claim => (
              <Card key={claim.id} className="field-card hover-lift">
                <CardHeader>
                  <div className="flex justify-between items-start">
                    <div>
                      <CardTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5" />
                        {claim.field?.name}
                      </CardTitle>
                      <CardDescription>
                        {claim.field?.crop_type} • {claim.field?.acreage} acres
                      </CardDescription>
                    </div>
                    <Badge variant={
                      claim.status === 'approved' ? 'default' :
                      claim.status === 'submitted' ? 'secondary' :
                      claim.status === 'denied' ? 'destructive' : 'outline'
                    }>
                      {claim.status}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div className="flex items-center gap-2">
                      <Calendar className="h-4 w-4 text-muted-foreground" />
                      <span>{new Date(claim.event_date).toLocaleDateString()}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <TrendingDown className="h-4 w-4 text-destructive" />
                      <span>{claim.estimated_loss_percentage}% Est. Loss</span>
                    </div>
                  </div>

                  <div className="p-3 bg-muted/50 rounded-lg">
                    <p className="text-sm font-medium mb-1">Event Type:</p>
                    <p className="text-sm text-muted-foreground capitalize">{claim.event_type}</p>
                  </div>

                  {claim.description && (
                    <div className="p-3 bg-muted/50 rounded-lg">
                      <p className="text-sm font-medium mb-1">Description:</p>
                      <p className="text-sm text-muted-foreground">{claim.description}</p>
                    </div>
                  )}

                  {claim.assessment && (
                    <div className="p-3 bg-muted/50 rounded-lg border border-primary/20">
                      <p className="text-sm font-medium mb-2">AI Assessment Data:</p>
                      <div className="grid grid-cols-2 gap-2 text-xs">
                        <div>
                          <span className="text-muted-foreground">Health Score:</span>
                          <span className="ml-2 font-semibold">{claim.assessment.health_score}/100</span>
                        </div>
                        <div>
                          <span className="text-muted-foreground">Stress Level:</span>
                          <span className="ml-2 font-semibold capitalize">{claim.assessment.stress_level}</span>
                        </div>
                      </div>
                    </div>
                  )}

                  <Button 
                    variant="outline" 
                    className="w-full gap-2"
                    onClick={() => exportClaim(claim.id)}
                  >
                    <Download className="h-4 w-4" />
                    Export Insurance Report
                  </Button>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
