-- ============================================================================
-- LSU AGCENTER SAFE SEEDING FILE (PRE-PARTNERSHIP VERSION)
-- ============================================================================

-- Insert LSU Researchers
INSERT INTO lsu_researchers (id, name, email, expertise, department, availability, research_areas, contact_preferences) VALUES
  ('550e8400-e29b-41d4-a716-446655440001', 'Dr. Sara Thomas-Sharma', 'agcenter@lsu.edu', ARRAY['soybean diseases', 'fungicide resistance', 'pathology', 'cercospora', 'frogeye leaf spot'], 'Plant Pathology', 'available', ARRAY['soybean diseases', 'cercospora blight', 'frogeye leaf spot', 'fungicide management'], '{"preferred_method": "email", "contact_email": "agcenter@lsu.edu", "response_time": "3-5 business days", "note": "Contact requests routed through LSU AgCenter partnership office", "requires_lsu_approval": true}'::JSONB),
  ('550e8400-e29b-41d4-a716-446655440002', 'Dr. Jim Wang', 'agcenter@lsu.edu', ARRAY['nitrogen management', 'precision agriculture', 'soil science', 'fertilizer efficiency'], 'Soil Science', 'available', ARRAY['nitrogen efficiency', 'precision fertilizer', 'climate smart', 'enhanced-efficiency fertilizers'], '{"preferred_method": "email", "contact_email": "agcenter@lsu.edu", "response_time": "3-5 business days", "note": "Contact requests routed through LSU AgCenter partnership office", "requires_lsu_approval": true}'::JSONB),
  ('550e8400-e29b-41d4-a716-446655440003', 'Dr. Eric Webster', 'agcenter@lsu.edu', ARRAY['rice agronomy', 'weed management', 'herbicide resistance', 'crop production'], 'Rice Agronomy', 'available', ARRAY['rice production', 'weed control', 'herbicide resistance', 'crop management'], '{"preferred_method": "email", "contact_email": "agcenter@lsu.edu", "response_time": "3-5 business days", "note": "Contact requests routed through LSU AgCenter partnership office", "requires_lsu_approval": true}'::JSONB),
  ('550e8400-e29b-41d4-a716-446655440004', 'Dr. Gerald Myers', 'agcenter@lsu.edu', ARRAY['rice breeding', 'genetics', 'disease resistance', 'variety development'], 'Plant Breeding', 'available', ARRAY['rice genetics', 'variety development', 'disease resistance breeding', 'quality traits'], '{"preferred_method": "email", "contact_email": "agcenter@lsu.edu", "response_time": "3-5 business days", "note": "Contact requests routed through LSU AgCenter partnership office", "requires_lsu_approval": true}'::JSONB)
ON CONFLICT (id) DO NOTHING;

-- Insert LSU Publications (Rice)
INSERT INTO lsu_publications (id, title, authors, year, url, crops, topics, key_findings, researcher_id, impact_score, farmer_views) VALUES
  ('LSU-PUB-001', 'Louisiana Rice Production Handbook', ARRAY['Dr. Eric Webster', 'Dr. Steve Linscombe'], 2023, 'https://www.lsuagcenter.com/portals/our_offices/research_stations/rice', ARRAY['rice'], ARRAY['rice production', 'variety selection', 'disease management'], ARRAY['Comprehensive rice production guidelines for Louisiana Delta', 'Variety performance data for Louisiana conditions', 'Integrated pest management strategies'], '550e8400-e29b-41d4-a716-446655440003', 0.95, 0),
  ('LSU-PUB-002', 'Rice Blast Disease Management in Louisiana', ARRAY['Dr. Don Groth'], 2022, 'https://www.lsuagcenter.com/topics/crops/rice/diseases', ARRAY['rice'], ARRAY['rice blast', 'disease management', 'fungicides'], ARRAY['Rice blast identification and management', 'Fungicide timing and selection', 'Resistant variety recommendations'], NULL, 0.92, 0),
  ('LSU-PUB-003', 'Soybean Production in Louisiana', ARRAY['Dr. Dan Fromme', 'Dr. David Moseley'], 2023, 'https://www.lsuagcenter.com/topics/crops/soybeans', ARRAY['soybeans'], ARRAY['soybean production', 'variety selection', 'best practices'], ARRAY['Louisiana soybean variety performance', 'Planting date optimization', 'Fertility management'], NULL, 0.93, 0),
  ('LSU-PUB-004', 'Managing Cercospora Blight in Louisiana Soybeans', ARRAY['Dr. Sara Thomas-Sharma'], 2022, 'https://www.lsuagcenter.com/topics/crops/soybeans/diseases', ARRAY['soybeans'], ARRAY['cercospora blight', 'disease management', 'fungicides'], ARRAY['Cercospora identification and lifecycle', 'Economic thresholds for treatment', 'Fungicide efficacy data'], '550e8400-e29b-41d4-a716-446655440001', 0.94, 0)
ON CONFLICT (id) DO NOTHING;